// src/lib/components/carrousel.svelte
<script lang="ts">
  import Arrow from '$lib/icons/arrow.svelte'
  import type { MainContent } from '$lib/types'
  import { LocalRotes } from '$lib/utils/routes'
  import Button from './button.svelte'
  import Link from './link.svelte'
  import Skeleton from './skeleton.svelte'

  let scrollContainer: HTMLDivElement

  export let type: MainContent
  export let data = [] as {
    malId: number
    title: string
    imageUrl: string
    topRightDataCard: number
  }[]

  function onScrollLeft() {
    const currentScroll = scrollContainer.scrollLeft
    scrollContainer.scrollTo({ behavior: 'smooth', left: currentScroll - 200 })
  }

  function onScrollRight() {
    const currentScroll = scrollContainer.scrollLeft
    scrollContainer.scrollTo({ behavior: 'smooth', left: currentScroll + 200 })
  }
</script>

<div class="mt-4 mb-2 flex justify-between gap-2">
  <slot name="title" />
  <div class="flex gap-2">
    <Button on:click={onScrollLeft} variant="text" class="bg-dark-v1 rounded px-1 text-primary active:translate-y-[2px] border border-tertiary"
      ><Arrow props={{ style: 'transform: rotate(-90deg);' }} /></Button
    >
    <Button on:click={onScrollRight} variant="text" class="bg-dark-v1 rounded px-1 text-secondary active:translate-y-[2px] border border-tertiary"
      ><Arrow props={{ style: 'transform: rotate(90deg);' }} /></Button
    >
  </div>
</div>
<div
  class="flex gap-4 w-full flex-nowrap mb-4 overflow-x-scroll snap-x relative items-center"
  style="scroll-behavior: smooth"
  id="container-carrousel"
  bind:this={scrollContainer}
>
  {#each data as item}
    <div
      class="rounded snap-center overflow-hidden align-middle flex-shrink-0 flex-grow-0 relative border-tertiary border-2"
      id={`to-${item.malId}`}
    >
      <Link href={LocalRotes[type].details(item.malId)}>
        <picture>
          <img
          class="hover:scale-105 duration-300 h-60 w-[160px] object-fill"
          src={item.imageUrl}
          alt={item.title}
          loading="lazy"
          />
        </picture>
      </Link>
      {#if item?.topRightDataCard}
        <div class="absolute top-1 right-1 bg-tertiary/70 rounded p-1 grid place-content-center">
          <span class="text-[.65rem] grid place-content-center">{item?.topRightDataCard}</span>
        </div>
      {/if}
      <div class="absolute bottom-1 mx-auto w-full">
        <div class="mx-1 bg-tertiary/60 rounded-sm backdrop-blur-[1px] h-fit">
          <h3 class="py-1 px-[6px] overflow-hidden text-ellipsis whitespace-nowrap hover:whitespace-normal duration-200 transition-all text-[.7rem]">
            {item.title}
          </h3>
        </div>
      </div>
    </div>
  {/each}
  {#if data.length === 0}
    {#each { length: 10 } as _}
      <div class="rounded snap-center overflow-hidden align-middle flex-shrink-0 flex-grow-0 w-fit">
        <Skeleton size={{ width: 'w-[160px]' }} />
      </div>
    {/each}
  {/if}
</div>

<style>
  #container-carrousel::-webkit-scrollbar:horizontal {
    height: 0;
  }
</style>

// components/Carrousel.tsx
import { useRef } from 'react'
import { ICarrousel } from 'interfaces/Anime'
import ArrowIcon from '../icons/ArrowIcon'
import { ButtonTransparent } from './Button'
import Link from 'next/link'
import { useRouter } from 'next/router'

interface Props {
  data: ICarrousel[]
  type?: 'anime' | 'manga' | 'character'
}

const Carrousel = ({ data, type }: Props) => {
  const router = useRouter()
  const refSlider = useRef<HTMLDivElement>(null)

  const scrollRight = () => {
    if (!refSlider.current) return

    (refSlider.current.clientWidth + refSlider.current.scrollLeft - refSlider.current.scrollWidth === 0)
      ? refSlider.current.scrollLeft = 0
      : refSlider.current.scrollLeft += 300
  }

  const scrollLeft = () => {
    if (!refSlider.current) return
    (refSlider.current?.scrollLeft !== 0)
      ? (refSlider.current.scrollLeft -= 300)
      : (refSlider.current.scrollLeft += refSlider.current.scrollWidth)
  }
  return (
    <div ref={refSlider} className='flex gap-4 w-full flex-nowrap my-4 overflow-x-scroll snap-x relative lg:h-80 h-64' style={{ scrollBehavior: 'smooth' }} id="container-carrousel">
      <div className='sticky left-0 z-[5] flex-shrink-0 flex-grow-0 rounded grid place-content-center'>
        <ButtonTransparent props={{ onClick: () => scrollLeft(), 'aria-label': 'arrow' }}><ArrowIcon props={{ style: { transform: 'rotate(180deg)' } }} /></ButtonTransparent>
      </div>
      {
        data?.map((anime) => (
          <div key={anime.mal_id} className='rounded-md snap-center overflow-hidden align-middle flex-shrink-0 flex-grow-0 relative' id={`to-${anime.mal_id}`}>
            <Link href={`/${type || router.query.type}/${anime?.mal_id}`}>
              <a>
                <img className='hover:scale-110 duration-300 h-full' src={anime.images.webp.image_url} alt={anime.title} />
              </a>
            </Link>
            {anime?.topRightgDataCard &&
              <div className='absolute top-2 right-2 bg-tertiary/70 rounded-lg p-1'>
                <span className='text-[.7rem]'>{anime?.topRightgDataCard}</span>
              </div>
            }
            <div className='absolute bottom-2 mx-auto w-full'>
              <div className='mx-2 bg-tertiary/70 rounded-lg'>
                <h2 className='text-sm p-2 overflow-hidden text-ellipsis whitespace-nowrap hover:whitespace-normal duration-300 transition-all'>{anime.title}</h2>
              </div>
            </div>
          </div>
        ))
      }
      <div className='sticky right-1 z-[5] flex-shrink-0 flex-grow-0 rounded grid place-content-center'>
        <ButtonTransparent props={{ onClick: () => scrollRight(), 'aria-label': 'arrow' }}><ArrowIcon /></ButtonTransparent>
      </div>
    </div>
  )
}

export default Carrousel
