// src/lib/components/footer.svelte
<script>
  import Share from '$lib/icons/share.svelte'
  import Arrow from '$lib/icons/arrow.svelte'

  import Button from './button.svelte'
  import Link from './link.svelte'

  const sharePage = () => {
    window.navigator.share({
      url: window.location.href,
      title: window.location.hostname
    })
  }

  const portfolioLink = 'https://frm-bot.vercel.app'

  const mailLink = 'mailto:damianmaciel0@gmail.com?subject=Feedback&body=Message'
</script>

<footer class="bg-dark-v1/70">
  <div class="w-full relative lg:max-w-[90vw] xl:max-w-screen-content max-w-[95vw] m-auto">
    <div class="absolute right-2 flex justify-end top-[-20%] z-10">
      <Button
        class="hover:-translate-y-1"
        on:click={() => window.scroll(0, 0)}
        props={{ 'aria-label': 'arrow', style: 'padding: 0.2rem;' }}
        ><Arrow props={{ style: 'rotate(-90deg)' }} /></Button
      >
    </div>
    <div class="py-4">
      <div class="flex mb-2">
        <p class="whitespace-nowrap flex items-center gap-2">
          Built and Design by <Link variant="text" href={portfolioLink} props={{ target: '_blank' }}
            >Maciel Franco</Link
          >
        </p>
      </div>
      <div class="flex items-center justify-end">
        <div class="flex gap-2">
          <Button props={{ 'on:click': () => sharePage(), 'aria-label': 'share' }}><Share /></Button
          >
          <Link variant="gradient" href={mailLink} props={{ target: '_blank' }}
            >damianmaciel0@gmail.com</Link
          >
        </div>
      </div>
    </div>
  </div>
</footer>

// components/Footer.tsx
import Button from 'components/Button'
import Link from './Link'
import ArrowIcon from 'icons/ArrowIcon'
import ShareIcon from 'icons/ShareIcon'

const Footer = () => {
  const sharePage = () => {
    window.navigator.share({
      url: window.location.href,
      title: window.location.hostname
    })
  }
  return (
    <footer className='relative'>
      <div className='absolute right-2 flex justify-end top-[-25%] z-10'>
        <Button props={{ onClick: () => window.scroll(0, 0), 'aria-label': 'arrow' }}><ArrowIcon props={{ style: { transform: 'rotate(-90deg)' } }} /></Button>
      </div>
      <div className='py-4 bg-secondary/70 rounded-md px-4 mb relative bottom-2'>

        <div className='flex mb-2'>
          <p className='whitespace-nowrap flex items-center gap-2'>Built and Design by <Link type='External' href='https://frm-bot.xyz'>Maciel Franco</Link></p>
        </div>
        <div className="flex items-center justify-end">
          <div className='flex gap-2'>
            <Button props={{ onClick: () => sharePage(), 'aria-label': 'share' }}><ShareIcon /></Button>
            <Link type='External' href='mailto:damianmaciel0@gmail.com?subject=Feedback&body=Message'>damianmaciel0@gmail.com</Link>
          </div>
        </div>
      </div>

    </footer>
  )
}

export default Footer
