// src/lib/components/header.svelte
<script>
  import { LocalRotes } from '$lib/utils/routes'
  import InputSearch from './inputSearch.svelte'
  import Link from './link.svelte'
</script>

<header class="sticky top-0 z-20 px-4 py-2 main-header duration-200" id="main-header">
  <nav
    class="w-full flex justify-between items-center z-20 sm:gap-2 gap-2 lg:max-w-[90vw] xl:max-w-screen-content max-w-[95vw] m-auto"
  >
    <Link href={LocalRotes.home}>Wiki Anime</Link>
    <ul class="flex gap-2 items-center">
      <li>
        <InputSearch />
      </li>
    </ul>
  </nav>
</header>

// components/Header.tsx
import InputSearch from './inputSearch'
import Link from 'next/link'

const Header = () => {
  return (
    <header className='sticky top-2 z-20 rounded-lg'>
    <nav className='w-full px-4 flex justify-between items-center z-20 border-b-[1px] border-solid border-tertiary bg-secondary/70 backdrop-blur-sm p-4 rounded-md sm:gap-2 gap-2 shadow-lg'>
      <Link href='/'>
          Wiki Anime
      </Link>
      <InputSearch />
    </nav>
  </header>
  )
}

export default Header
