// src/lib/components/pagination.svelte
<script lang="ts">
  import Button from './button.svelte'
  import ArrowIcon from '$lib/icons/arrow.svelte'
  import Card from './card.svelte'
  import { page } from '$app/stores'
  import { goto } from '$app/navigation'
  import { fromObjectQueriesToUrl } from '$lib/utils/url'
  $: search = Object.fromEntries(new URLSearchParams($page.url.search))

  export let info = {
    current_page: Number(search.page) ?? 1,
    last_visible_page: 1,
    has_next_page: false
  }

  $: baseUrl = $page.url.origin + $page.url.pathname

  function nextPage() {
    if (info.current_page < info.last_visible_page) {
      info.current_page++
      const toUrl = fromObjectQueriesToUrl({
        baseUrl,
        queries: {
          ...search,
          page: String(info.current_page)
        }
      })
      goto(String(toUrl))
    }
  }
  function previousPage() {
    if (info.current_page > 1) {
      info.current_page--
      const toUrl = fromObjectQueriesToUrl({
        baseUrl,
        queries: {
          ...search,
          page: String(info.current_page)
        }
      })
      goto(String(toUrl))
    }
  }

  function goToPage({ page = 1 }: { page: number }) {
    if (page <= info.last_visible_page && page > 0) {
      info.current_page = page
      const toUrl = fromObjectQueriesToUrl({
        baseUrl,
        queries: {
          ...search,
          page: String(info.current_page)
        }
      })
      goto(String(toUrl))
    }
  }
</script>

<div class="w-full grid place-content-center">
  <Card class="my-2 w-fit">
    <div class="flex gap-4 justify-center items-center">
      <Button on:click={previousPage} props={{ style: 'padding: 3px;', disabled: info.current_page === 1 }}>
        <ArrowIcon props={{ style: 'transform: rotate(-90deg);' }} />
      </Button>

      <input
        class="bg-dark-v2 [-webkit-appearance: none] h-full text-center p-2 focus:outline-none appearance-none w-16"
        placeholder="page"
        type="number"
        bind:value={info.current_page}
        min="1"
        max={info.last_visible_page}
        on:keypress={(e) => e.key === 'Enter' && goToPage({ page: Number(e.currentTarget.value) })}
        required
      />
      <span>of</span>
      <span>{info.last_visible_page}</span>

      <Button on:click={nextPage} props={{ style: 'padding: 3px;', disabled: !info.has_next_page }}>
        <ArrowIcon props={{ style: 'transform: rotate(90deg);' }} />
      </Button>
      <Button
        on:click={(_) => {
          goToPage({ page: info.current_page })
        }}
        props={{ style: 'padding: 3px 10px;' }}>Go</Button
      >
    </div>
  </Card>
</div>

// components/Pagination.tsx
import { useRef, useEffect } from 'react'
import Button from './Button'
import Card from './Card'
import { useRouter } from 'next/router'
import ArrowIcon from '../icons/ArrowIcon'

interface IProps {
  currentPage: number
  lastPage: number
}

const Pagination = ({ currentPage, lastPage }: IProps) => {
  const refInput = useRef<HTMLInputElement>(null)
  const router = useRouter()
  useEffect(() => {
    if (!refInput.current) return
    refInput.current.value = currentPage?.toString()
  }, [currentPage])

  const handlerGo = () => {
    if (!refInput.current) return
    const page = Number(refInput.current.value) || 1
    if (page <= lastPage && page >= 1) {
      const { type, ...rest } = router.query
      router.push({
        pathname: window?.location?.pathname,
        query: {
          ...rest,
          page
        }
      })
    }
  }
  const handlerNextPage = () => {
    if (currentPage <= lastPage) {
      const { type, ...rest } = router.query
      router.push({
        pathname: window?.location?.pathname,
        query: {
          ...rest,
          page: currentPage + 1
        }
      })
    }
  }
  const handlerPrevPage = () => {
    if (currentPage > 1) {
      const { type, ...rest } = router.query
      router.push({
        pathname: window?.location?.pathname,
        query: {
          ...rest,
          page: currentPage - 1
        }
      })
    }
  }

  return (
    <div className='w-full grid place-content-center'>
      <Card className='my-4 w-fit'>
        <div className='flex gap-4 justify-center items-center'>

          <Button props={{ disabled: currentPage === 1, onClick: () => handlerPrevPage(), 'aria-label': 'arrow' }}>
            <ArrowIcon props={{ style: { transform: 'rotate(180deg)' } }} />
          </Button>

          <div className='flex gap-2'>
            <input ref={refInput} onKeyDown={(e) => e.code === 'Enter' && handlerGo()} className='bg-primary [-webkit-appearance: none] h-full text-center p-2 focus:outline-none appearance-none w-16' placeholder='page' type="number" min='1' max={lastPage} defaultValue={currentPage} />
            <Button props={{ onClick: () => handlerGo() }}>Go</Button>
          </div>
          <span>of</span>
          <span>{lastPage}</span>

          <Button props={{ disabled: currentPage === lastPage, onClick: () => handlerNextPage() }}>
            <ArrowIcon props={{ 'aria-label': 'arrow' }} />
          </Button>
        </div>
      </Card>
    </div>
  )
}

export default Pagination
