// src/routes/[type]/[id]/+page.svelte
<script lang="ts">
  import { fly } from 'svelte/transition'
  import Characters from '$lib/components/characters.svelte'
  import Link from '$lib/components/link.svelte'
  import SectionSubTitleCard from '$lib/components/sectionSubTitleCard.svelte'
  import SubSection from '$lib/components/subSection.svelte'
  import type { Anime } from '$lib/types/anime'
  import type { Manga } from '$lib/types/manga'
  import type { PageData } from './$types'
  import { MainContentData } from '$lib/types'
  import { LocalRotes } from '$lib/utils/routes'
  import Details from '$lib/components/details.svelte'
  import { page } from '$app/stores'
  import Card from '$lib/components/card.svelte'

  export let data: PageData
  function checkIsAnime(data: Anime | Manga): data is Anime {
    return (data as Anime).episodes !== undefined
  }
  const classSubtitleSection =
    'text-center bg-dark-v1 flex items-center justify-center px-4 py-2 w-full'
  $: type = $page.params.type as MainContentData
</script>

<svelte:head>
  <title>
    {data?.title || ''}
  </title>
</svelte:head>

<Details
  info={{ imgSrc: data?.images?.webp?.image_url, mainTitle: data?.title, mal_id: data.mal_id }}
>
  <div slot="left-section" transition:fly={{ x: -200, duration: 200 }} class="flex flex-col gap-4">
    <h3 class={classSubtitleSection}>Alternative Titles</h3>
    <SubSection title="Synonyms" data={data?.title_synonyms} />
    <SubSection title="Japanese" description={data?.title_japanese} />
    <SubSection title="English" description={data?.title_english} />

    <h3 class={classSubtitleSection}>Information</h3>
    <SubSection title="Type">
      <Link
        variant="gradient"
        href={LocalRotes.search({
          type,
          queries: { type: data.type.replaceAll(' ', '').toLowerCase() }
        })}>{data?.type}</Link
      >
    </SubSection>

    {#if checkIsAnime(data)}
      <SubSection title="Aired" description={data?.aired?.string} />
      <SubSection title="Episodes" description={data?.episodes} />
      <SubSection title="Duration" description={data?.duration} />
      {#if data?.season && data?.year}
        <SubSection title="Season">
          <Link
            variant="gradient"
            href={LocalRotes.anime.season.to({ season: data.season, year: data.year })}
          >
            {data?.season}
            {data?.year}
          </Link>
        </SubSection>
      {/if}
      {#if data?.broadcast?.string}
        <SubSection title="Broadcast" description={data?.broadcast?.string} />
      {/if}
      <SubSection title="Studios">
        {#each data?.studios as studio}
          <!-- <Link variant="gradient" href={LocalRotes.studio.details(studio.mal_id)}
            >{studio?.name}</Link -->
          <Card variant="gradient-v2">{studio?.name}</Card>
        {/each}
      </SubSection>

      {#if data?.licensors?.length > 0}
        <SubSection title="Licensors">
          {#each data?.licensors as licensor}
            <!-- <Link variant="gradient" href={`/${licensor?.type}/genres/${licensor?.mal_id}`}
              >{licensor?.name}</Link
            > -->
            <Card variant="gradient-v2">{licensor?.name}</Card>
          {/each}
        </SubSection>
      {/if}
    {:else}
      <SubSection title="Published" description={data?.published?.string} />
      <SubSection title="Authors">
        {#each data?.authors as author}
          <Link variant="gradient" href={LocalRotes.people.details({ id: author.mal_id })}
            >{author?.name}</Link
          >
        {/each}
      </SubSection>
    {/if}
    <SubSection title="Status" description={data?.status} />
    <SubSection title="Source" description={data?.source} />
    <SubSection title="Rating" description={data?.rating} />
    <SubSection title="Genres">
      {#each data?.genres as genre}
        <Link
          variant="gradient"
          href={LocalRotes.search({ type, queries: { genres: String(genre.mal_id) } })}
          >{genre?.name}</Link
        >
      {/each}
    </SubSection>

    <SubSection title="Themes">
      {#each data?.themes as theme}
        <Link
          variant="gradient"
          href={LocalRotes.search({ type, queries: { genres: String(theme.mal_id) } })}
          >{theme?.name}</Link
        >
      {/each}
    </SubSection>

    <SubSection title="Demographics">
      {#each data?.demographics as demographic}
        <Link
          variant="gradient"
          href={LocalRotes.search({ type, queries: { genres: String(demographic.mal_id) } })}
          >{demographic?.name}</Link
        >
      {/each}
    </SubSection>

    <h3 class={classSubtitleSection}>Statistics</h3>
    <SubSection title="Rank" description={data?.rank} />
    <SubSection title="Score" description={data?.score} />
    <SubSection title="Scored by" description={data?.scored_by} />
    <SubSection title="Popularity" description={data?.popularity} />
    <SubSection title="Members" description={data?.members} />
    <SubSection title="Favorites" description={data?.favorites} />

    <h3 class={classSubtitleSection}>External Links</h3>
    {#if data.external}
      <div class="flex flex-wrap gap-2">
        {#each data?.external as link}
          <Link variant="gradient" href={link.url} props={{ target: '_blank', rel: 'noreferrer' }}>
            {link.name}
          </Link>
        {/each}
        <Link
          variant="gradient"
          props={{ target: '_blank' }}
          href={`https://lectortmo.com/library?_pg=1&title=${data?.title}`}>{data?.title}</Link
        >
      </div>
    {/if}
  </div>
  <div
    slot="right-section"
    transition:fly={{ x: 200, duration: 200 }}
    class="flex flex-col gap-4 backdrop-blur-sm"
  >
    <SectionSubTitleCard>Synopsis</SectionSubTitleCard>
    <p>{data?.synopsis}</p>
    {#if data?.background}
      <SectionSubTitleCard>Background</SectionSubTitleCard>
      <p>{data?.background}</p>
    {/if}

    <Characters
      id={data?.mal_id}
      type={checkIsAnime(data) ? MainContentData.Anime : MainContentData.Manga}
    />

    <SectionSubTitleCard>Related</SectionSubTitleCard>
    {#each data?.relations as relation}
      <SubSection title={relation?.relation}>
        {#each relation?.entry as entry}
          <Link variant="gradient" href={`/${entry.type}/${entry.mal_id}`}>{entry.name}</Link>
        {/each}
      </SubSection>
    {/each}
    {#if checkIsAnime(data) && data?.trailer?.embed_url}
      <SectionSubTitleCard>Trailer</SectionSubTitleCard>
      <iframe
        loading="lazy"
        title="trailer"
        class="aspect-video w-full"
        src={data?.trailer?.embed_url}
        allowFullScreen
      />
    {/if}
  </div>
</Details>

// pages/[type]/[id].tsx
import { Button, ButtonLink, LinkExternal } from 'components/Button'
// import Card from 'components/Card'
import { IAnimeManga } from 'interfaces/Global'
import { GET_DETAILS } from 'services/GET_DETAILS'
import { useRouter } from 'next/router'
import { useState } from 'react'
import { CardLink } from 'components/Cards'
import { SubtitleCard, TitleAndDescription } from 'components/Text'
import ImageComponent from 'components/Image'
import ValidateAndRender from 'components/ValidateAndRender'
import SectionInfo from 'components/SectionInfo'
import { useFetch } from 'utils/useFetch'
import { URL_CHARACTERS } from 'services/endpoints'
import LayoutDetails from 'Layouts/LayoutDetails'
import type { GetServerSideProps } from 'next'
import LoadingComponent from 'components/LoadingComponent'

interface ICharacter {
  character: {
    mal_id: number,
    url: string,
    images: {
      jpg: {
        image_url: string,
        small_image_url: string
      },
      webp: {
        image_url: string,
        small_image_url: string
      }
    },
    name: string
  },
  role: string
}
interface IResponseCharacters {
  data: { data: ICharacter[] }
  isLoading: boolean
  isError: any
}

interface IProps {
  details: IAnimeManga
  characters: ICharacter[]
  type: string
}

const Details = ({ details, type }: IProps) => {
  const router = useRouter()
  const { data: characters, isError, isLoading }: IResponseCharacters = useFetch(URL_CHARACTERS(type, details?.mal_id))

  const [isShowAllCharacters, setIsShowAllCharacters] = useState(false)
  const handlerShowAllCharacters = () => {
    setIsShowAllCharacters(prevValue => !prevValue)
  }
  return (
    <LayoutDetails h1={details?.title} h2={details?.title_english}>
      <>
        {/* Left part */}
        <div className='flex flex-col gap-4'>
          <ImageComponent src={details?.images?.webp?.large_image_url} alt={details?.title} />
          <SectionInfo title='Alternative Titles'>
            <>
              <ValidateAndRender title='Synonyms' dataToValidate={[details?.title_synonyms?.length]}>
                <>{details?.title_synonyms?.map((synonym) => (<span className='bg-tertiary p-2 shadow-lg' key={synonym}>{synonym}</span>))}</>
              </ValidateAndRender>

              <ValidateAndRender title='Japanese' data={details?.title_japanese} />

              <ValidateAndRender title='English' data={details?.title_english} />
            </>
          </SectionInfo>
          <SectionInfo title='Information'>
            <>
              <TitleAndDescription title='Type'><ButtonLink href={`/${router.query.type}/top/${details?.type?.toLowerCase().replace(' ', '')}`}>{details?.type}</ButtonLink></TitleAndDescription>
              <ValidateAndRender title='Episodes' data={details?.episodes} />
              <ValidateAndRender title='Duration' data={details?.duration} />
              <ValidateAndRender title='Status' data={details?.status} />
              <ValidateAndRender title='Aired' data={details?.aired?.string} />
              <ValidateAndRender title='Published' data={details?.published?.string} />
              <ValidateAndRender title='Season' dataToValidate={[details?.season, details?.year]}>
                <ButtonLink href={`/anime/season/${details?.season}/${details?.year}`}>{`${details?.season} ${details?.year}`}</ButtonLink>
              </ValidateAndRender>
              <ValidateAndRender title='Genres' dataToValidate={[details?.genres?.length]}>
                <>{details?.genres?.map((genre) => (<ButtonLink href={`/${genre?.type?.toLowerCase()}/genres/${genre?.mal_id}`} key={genre?.mal_id}>{genre?.name}</ButtonLink>))}</>
              </ValidateAndRender>
              <ValidateAndRender title='Source' data={details?.source} />
              <ValidateAndRender title='Broadcast' data={details?.broadcast?.string} />
              <ValidateAndRender title='Rating' data={details?.rating} />
              <ValidateAndRender title='Themes' dataToValidate={[details?.themes?.length]}>
                <>{details?.themes?.map((theme) => (<ButtonLink href={`/${theme?.type?.toLowerCase()}/genres/${theme?.mal_id}`} key={theme?.mal_id}>{theme?.name}</ButtonLink>))}</>
              </ValidateAndRender>
              <ValidateAndRender title='Authors' dataToValidate={[details?.authors]}>
                <>{details?.authors?.map((author) => (<ButtonLink href={`/${author?.type?.toLowerCase()}/${author?.mal_id}`} key={author?.mal_id}>{author?.name}</ButtonLink>))}</>
              </ValidateAndRender>
              <ValidateAndRender title='Studios' dataToValidate={[details?.studios?.length]}>
                <>{details?.studios?.map((studio) => (<ButtonLink href={`/${studio?.type?.toLowerCase()}/producer/${studio?.mal_id}`} key={studio?.mal_id}>{studio?.name}</ButtonLink>))}</>
              </ValidateAndRender>
              <ValidateAndRender title='Demographics' dataToValidate={[details?.demographics?.length]}>
                <>{details?.demographics?.map((demographic) => (<ButtonLink href={`/${demographic?.type.toLowerCase()}/genres/${demographic?.mal_id}`} key={demographic?.mal_id}>{demographic?.name}</ButtonLink>))}</>
              </ValidateAndRender>
              <ValidateAndRender title='Licensors' dataToValidate={[details?.licensors?.length]}>
                <>{details?.licensors?.map((licensor) => (<ButtonLink href={`/${licensor?.type?.toLowerCase()}/producer/${licensor?.mal_id}`} key={licensor?.mal_id}>{licensor?.name}</ButtonLink>))}</>
              </ValidateAndRender>
            </>
          </SectionInfo>
          <SectionInfo title='Statistics'>
            <>
              <ValidateAndRender title='Rank' data={details?.rank} />
              <ValidateAndRender title='Score' data={details?.score} />
              <ValidateAndRender title='Scored by' data={details?.scored_by} />
              <ValidateAndRender title='Popularity' data={details?.popularity} />
              <ValidateAndRender title='Members' data={details?.members} />
              <ValidateAndRender title='Favorites' data={details?.favorites} />
            </>
          </SectionInfo>
          <SectionInfo title='External Links'>
            <>
              <ValidateAndRender dataToValidate={[details?.external]}>
                <>{details?.external?.map((link) => (<LinkExternal href={link?.url} key={link?.name}>{link?.name || link?.url}</LinkExternal>))}</>
              </ValidateAndRender>

              <TitleAndDescription title='TMO'>
                <LinkExternal href={`https://lectortmo.com/library?_pg=1&title=${details?.title}`}>{details?.title}</LinkExternal>
              </TitleAndDescription>
            </>
          </SectionInfo>
        </div>
        {/* Right part */}
        <div className='flex flex-col gap-6'>
          <ValidateAndRender dataToValidate={[details?.synopsis]}>
            <SectionInfo title='Synopsis'>
              <p className=''>{details?.synopsis}</p>
            </SectionInfo>
          </ValidateAndRender>
          <ValidateAndRender dataToValidate={[details?.background]}>
            <SectionInfo title='Background'>
              <p>{details?.background}</p>
            </SectionInfo>
          </ValidateAndRender>
          <div>
            <SubtitleCard>
              <div className='flex justify-between items-center'>
                <h3>Characters</h3>
                <Button props={{ onClick: () => handlerShowAllCharacters() }}><> {isShowAllCharacters ? 'Show less' : `All characters(${characters?.data?.length || '0'})`}</></Button>
              </div>
            </SubtitleCard>

            <LoadingComponent isError={isError} isLoading={isLoading}>
              <div className='grid 2xl:grid-cols-5 xl:grid-cols-5 lg:grid-cols-3 md:grid-cols-4 sm:grid-cols-3 grid-cols-2 gap-2 my-4'>
                {
                  characters?.data?.slice(0, isShowAllCharacters ? characters?.data?.length : 10)?.map(({ character, role }: ICharacter) => (
                    <CardLink key={character.mal_id} href={`/character/${character?.mal_id}`} imageSrc={character.images.webp.image_url} title={character.name} subtitle={role} />
                  ))
                  }
              </div>
            </LoadingComponent>
            <ValidateAndRender dataToValidate={[details?.relations?.length]}>
              <SectionInfo title='Related'>
                <>
                  {
                    details?.relations?.map((relation) => (
                      <TitleAndDescription title={relation?.relation} key={relation?.relation}>
                        <>
                          {
                            relation?.entry.map(({ mal_id, name, type }: any) => (<ButtonLink href={`/${type}/${mal_id}`} key={mal_id}>{name}</ButtonLink>))
                          }
                        </>
                      </TitleAndDescription>
                    ))
                  }
                </>
              </SectionInfo>
            </ValidateAndRender>
          </div>
          <ValidateAndRender dataToValidate={[details?.trailer?.embed_url]}>
            <SectionInfo title='Trailer'>
              <iframe loading='lazy' className='aspect-video w-full' src={details?.trailer?.embed_url} allowFullScreen />
            </SectionInfo>
          </ValidateAndRender>
        </div>
      </>
    </LayoutDetails >
  )
}

export const validateTypeAnimeManga = (str: string | string[] | undefined): 'anime' | 'manga' => {
  if (typeof str === 'string') {
    if (str === 'anime') {
      return str
    }
    if (str === 'manga') {
      return str
    }
  }
  return 'anime'
}

export const getServerSideProps: GetServerSideProps = async ({ res, query }) => {
  try {
    const { type, id } = query
    const details = await GET_DETAILS({ id: Number(id) ?? 9, type: validateTypeAnimeManga(type) })
    if (!details?.data) {
      return {
        notFound: true
      }
    }
    res.setHeader(
      'Cache-Control',
      'public, s-maxage=10, stale-while-revalidate=59'
    )
    return {
      props: {
        details: details?.data,
        type
      }
    }
  } catch (error: Error | any) {
    console.error(error)
    return { props: { errors: error?.message } }
  }
}

export default Details
